chmod +x ./aes/aes/aes && echo ./aes/aes/aes && ./aes/aes/aes ./aes/aes/input.data ./aes/aes/check.data
chmod +x ./bfs/bulk/bfs && echo ./bfs/bulk/bfs && ./bfs/bulk/bfs ./bfs/bulk/input.data ./bfs/bulk/check.data
chmod +x ./bfs/queue/bfs && echo ./bfs/queue/bfs && ./bfs/queue/bfs ./bfs/queue/input.data ./bfs/queue/check.data
chmod +x ./fft/strided/fft && echo ./fft/strided/fft && ./fft/strided/fft ./fft/strided/input.data ./fft/strided/check.data
chmod +x ./fft/transpose/fft && echo ./fft/transpose/fft && ./fft/transpose/fft ./fft/transpose/input.data ./fft/transpose/check.data
chmod +x ./gemm/ncubed/gemm && echo ./gemm/ncubed/gemm && ./gemm/ncubed/gemm ./gemm/ncubed/input.data ./gemm/ncubed/check.data
chmod +x ./gemm/blocked/gemm && echo ./gemm/blocked/gemm && ./gemm/blocked/gemm ./gemm/blocked/input.data ./gemm/blocked/check.data
chmod +x ./kmp/kmp/kmp && echo ./kmp/kmp/kmp && ./kmp/kmp/kmp ./kmp/kmp/input.data ./kmp/kmp/check.data
chmod +x ./md/knn/md && echo ./md/knn/md && ./md/knn/md ./md/knn/input.data ./md/knn/check.data
chmod +x ./md/grid/md && echo ./md/grid/md && ./md/grid/md ./md/grid/input.data ./md/grid/check.data
chmod +x ./nw/nw/nw && echo ./nw/nw/nw && ./nw/nw/nw ./nw/nw/input.data ./nw/nw/check.data
chmod +x ./sort/merge/sort && echo ./sort/merge/sort && ./sort/merge/sort ./sort/merge/input.data ./sort/merge/check.data
chmod +x ./sort/radix/sort && echo ./sort/radix/sort && ./sort/radix/sort ./sort/radix/input.data ./sort/radix/check.data
chmod +x ./spmv/crs/spmv && echo ./spmv/crs/spmv && ./spmv/crs/spmv ./spmv/crs/input.data ./spmv/crs/check.data
chmod +x ./spmv/ellpack/spmv && echo ./spmv/ellpack/spmv && ./spmv/ellpack/spmv ./spmv/ellpack/input.data ./spmv/ellpack/check.data
chmod +x ./stencil/stencil2d/stencil && echo ./stencil/stencil2d/stencil && ./stencil/stencil2d/stencil ./stencil/stencil2d/input.data ./stencil/stencil2d/check.data
chmod +x ./stencil/stencil3d/stencil && echo ./stencil/stencil3d/stencil && ./stencil/stencil3d/stencil ./stencil/stencil3d/input.data ./stencil/stencil3d/check.data
chmod +x ./viterbi/viterbi/viterbi && echo ./viterbi/viterbi/viterbi && ./viterbi/viterbi/viterbi ./viterbi/viterbi/input.data ./viterbi/viterbi/check.data